### ISSUE TITLE
ssl can't read large files in a single read()

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#46]
```
Traceback (most recent call last):
  File "/Users/csh/test.py", line 10, in <module>
    test_blobfile_download()
  File "/Users/csh/test.py", line 6, in test_blobfile_download
    raw_chkpt_bytes = blobfile.BlobFile(piece_path_gcs, mode="rb").read()
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/blobfile/ops.py", line 1597, in readall
    opt_bytes = self.read(self._size - self._offset)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/blobfile/ops.py", line 1618, in readinto
    opt_n = self._f.readinto(b)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/response.py", line 661, in readinto
    temp = self.read(len(b))
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/site-packages/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/http/client.py", line 447, in read
    n = self.readinto(b)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/http/client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/csh/miniconda3/envs/openai/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
OverflowError: signed integer is greater than maximum
```

The file size in this case is `2287476709` which is > `2**31`

**Comment by christopherhesse** [comment]
This could be fixed by reading smaller chunks or finding some sentinel value to pass to read everything, though it's unclear what that would be here, since `.read(-1)` just calls `readall`

**Comment by nottombrown** [comment]
Hmm. Maybe in the meantime we could throw an error that points the user at your workaround if they try to download a file that's larger than 2**31 bytes?

**Comment by christopher-hesse** [comment]
The workaround I posted is the same as option 1.  I intend to implement one of these fixes but may not have time today.
