### ISSUE TITLE
support AZURE_STORAGE_AUTH_MODE=login

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#68]
Looks like blobfile uses the key method now, should support this new fancy method

**Comment by christopherhesse** [comment]
```
from azure.common.credentials import get_azure_cli_credentials
creds, sub_id = get_azure_cli_credentials(resource=f'https://{account_name}.blob.core.windows.net/')
```

**Comment by christopherhesse** [comment]
https://github.com/Azure/azure-sdk-for-python/blob/fb4b717d1a681742929f170124577f95d61d210a/sdk/core/azure-common/azure/common/credentials.py#L59

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/_profile.py#L540

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/adal_authentication.py#L17

**Comment by christopherhesse** [comment]
Might be that the scope is wrong on the existing access token.  Also might be possible to run something like `az account get-access-token` if all else fails.

**Comment by christopherhesse** [comment]
`az account get-access-token --resource https://<account>.blob.core.windows.net/` seems to produce useful access tokens

**Comment by christopherhesse** [comment]
Looks like scope for the access token request can be `f"https://{account}.blob.core.windows.net/"` and this seems to work

**Comment by christopher-hesse** [comment]
This fails with my account, oddly:

```
az storage container list --account-name cshteststorage2

You do not have the required permissions needed to perform this operation.
Depending on your operation, you may need to be assigned one of the following roles:
    "Storage Blob Data Contributor"
    "Storage Blob Data Reader"
    "Storage Queue Data Contributor"
    "Storage Queue Data Reader"

If you want to use the old authentication method and allow querying for the right account key, please use the "--auth-mode" parameter and "key" value.

The command failed with an unexpected error. Here is the traceback:

'CommandResultItem' object is not iterable
Traceback (most recent call last):
  File "C:\tools\miniconda3\envs\blobfile\lib\site-packages\knack\cli.py", line 212, in invoke
    self.output.out(cmd_result, formatter=formatter, out_file=out_file)
  File "C:\tools\miniconda3\envs\blobfile\lib\site-packages\knack\output.py", line 132, in out
    output = formatter(obj)
  File "C:\tools\miniconda3\envs\blobfile\lib\site-packages\knack\output.py", line 38, in format_json
    input_dict = dict(result) if hasattr(result, '__dict__') else result
TypeError: 'CommandResultItem' object is not iterable
```
